spring:
  application:
    name: chislius_server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

config:
  room:
    capacity:
      public: 3
      private:
        min: 2
        max: 6
  game:
    wrong-move-cost: -3